
development:
  adapter: mysql2
  database: showv_development
  username: root
  password: 
  timeout: 5000



test:
  adapter: mysql2
  database: showv_test
  username: root
  password: 
  timeout: 5000
