

development:
  host: localhost
  database: ish_development
  sessions:
    default:
      database: ish_development
      hosts:
        - localhost:27017

test:
  host: localhost
  database: ish_test
  sessions:
    default:
      database: ish_test
      hosts:
        - localhost:27017
        
        
        